```{r}
datos <- data.frame(var1=rpois(50, 6), var2=rgamma(50, shape=5,rate=.4), var3=rnorm(50, 10))
datos %>% 
    select(var2) %>% 
    as.list %>% 
    names
```

```{r, eval=FALSE}
library(correlation)
library(corrr)
library(tidyr)
library(dplyr)
library(Hmisc)
#CORRELACIONES PARA VER DESPUÉS
#https://journals.sagepub.com/doi/pdf/10.1177/8756479308317006
corre <- base %>% 
  dplyr::select(i1_m1:i35_m1) %>% 
  rename_all(function(x) substr(x, 1, nchar(x)-3)) %>% 
  correlation(method = "tetrachoric") %>% 
  summary(redundant = TRUE) %>%
  as.data.frame()
row.names(corre) <- corre$Parameter
corre <- corre[,-1]
corre <- as.matrix(corre)

network_plot(corre, min_cor=.5, colours = c("red", "white", "blue"))
na.omit(starwars) %>% 
correlation(., method = "auto") %>% 
  as.data.frame %>%
  network_plot(.)
  select(r)

df %>% 
select(cont1, nomi1) %>%   
correlation(., method = "auto")

df <- carData::Salaries %>% 
    mutate(ordi=factor(sample(1:5, 397, replace = TRUE), ordered = TRUE))

df <- data.frame(cont1=rnorm(100), 
                 cont2=rnorm(100),
                 ordi1=factor(sample(1:5, 100, replace = TRUE), ordered = TRUE),
                 ordi2=factor(sample(1:7, 100, replace = TRUE), ordered = TRUE),
                 bin1=rbinom(100, 1, .4),
                 bin2=rbinom(100, 1, .6),
                 nomi1=factor(sample(letters[1:8], 100, replace = TRUE)),
                 nomi2=factor(sample(LETTERS[1:8], 100, replace = TRUE)))

x <- correlate(mtcars)
network_plot(x)
```

```{r}
clases <- function(data){
  class1 <- lapply(data, class)
  
  #Continuous variables
  cont_vars <- sapply(class1, function(x){
    sum(x %in% c("numeric", "double", "integer"))
  })
  cont_vars <- which(cont_vars>=1)
  
  if(length(cont_vars)>0){
    cont_vars <- cont_vars[sapply(data[,cont_vars], function(x){
      (sum((x%%1)<1 & (x%%1)>0)>nrow(data)*.20) | (length(table(x))>2)
    })]}
  #Binary variables
  bin_vars <- sapply(class1, function(x){
    sum(x %in% c("numeric", "double", "integer", "factor", "ordered"))
  })    
  
  bin_vars <- which(bin_vars>=1)
  
  if(length(bin_vars)>0){
    bin_vars <- bin_vars[sapply(data[,bin_vars], function(x){
      (length(table(x))=="2")
    })]}
  #Ordinal variables
  ord_vars <- sapply(class1, function(x){
    sum(x %in% c("ordered"))
  })
  
  ord_vars <- which(ord_vars>=1)
  
  if(length(ord_vars)>0 & length(levels(data[,ord_vars]))>2){
    ord_vars <- ord_vars[sapply(data[,ord_vars], function(x){
      ("ordered" %in% class(x)) | (if(sum(grepl("\\D", levels(x)))<1){
        if(length(which(diff(as.numeric(levels(x))) != 1))<1){
          TRUE
        }else(FALSE)
      }else(FALSE))
    })]}
  #Nominal variables
  nom_vars <- sapply(class1, function(x){
    sum((x %in% c("factor") & length(x)=="1"))
  })
  
  nom_vars <- which(nom_vars>=1)
  
  if(length(nom_vars)>0 & length(levels(data[,nom_vars]))>2){
    nom_vars <- nom_vars[sapply(data[,nom_vars], function(x){
      ("ordered" %nin% class(x)) & (sum(grepl("\\D", levels(x)))>0)
    })]}
  
  types <- list(continuous = names(cont_vars), 
                binary = names(bin_vars),
                ordinal = names(ord_vars)[names(ord_vars)%nin%names(bin_vars)],
                nominal = names(nom_vars)[names(nom_vars)%nin%names(bin_vars)])
  types <- types[which(sapply(types, length)>0)]
  
  #Recoding binary variables
  if("binary"%in% names(types)){
    data <- mutate_at(data, vars(types$binary), as.numeric)
  }
  
  types <- lapply(types, function(x){
    as.data.frame(x)
  }) %>% 
    do.call(rbind, .) %>% 
    mutate(class=unlist(mapply(rep, names(types), sapply(types, length), SIMPLIFY = FALSE))) %>% 
    rename("variable"="x")
  
  stages <- as.data.frame(t(combn(types$variable, 2))) %>% 
    left_join(.,types, by=c("V1"="variable")) %>% 
    rename(V1_class=class) %>% 
    left_join(.,types, by=c("V2"="variable")) %>% 
    rename(V2_class=class)
  
  cor_types <- data.frame(V1_class=c("continuous", "continuous", "continuous", "continuous", "ordinal", 
                                     "ordinal", "ordinal", "binary", "binary", "nominal"),
                          V2_class=c("continuous", "ordinal", "binary", "nominal", "ordinal",
                                     "binary", "nominal", "binary", "nominal", "nominal"),
                          cor_type=c("pearson", "kendall", "point-biserial", "biserial", "polychoric",
                                     "rank-biserial", "kruskal", "tetrachoric", "kruskal", "kruskal"))
  cor_types <- do.call(rbind, list(cor_types, {
    cor_types %>%
      rename(V1_class=V2_class,
             V2_class=V1_class) %>%
      select(V1_class, V2_class, cor_type)
  })) %>%
    unique %>% 
    left_join(stages, ., by=c("V1_class", "V2_class"))
  
  cor_types <- cor_types %>% 
    mutate(r=ifelse(cor_type %in% c("pearson", "kendall", "spearman", "point-biserial","biserial", "polychoric",
                                    "tetrachoric", "biweight", "distance", "percentage", "shepherd"),
                    paste("as.data.frame(correlation(select(data,", V1,",", V2, "), method='", cor_type, "'))", sep=""),
                    NA),
           r=ifelse(V1_class=="continuous" & V2_class=="ordinal", 
                    paste("as.data.frame(correlation(mutate(select(data,", V1,",", V2, "),", V2,"=as.numeric(", V2,")), method='", cor_type, "',include_factors=TRUE))$tau", sep=""),
                    ifelse(V1_class=="ordinal" & V2_class=="continuous",
                           paste("as.data.frame(correlation(mutate(select(data,", V2,",", V1, "),", V1,"=as.numeric(", V1,")), method='", cor_type, "',include_factors=TRUE))$tau", sep=""),
                           r)),
           r=ifelse(V1_class=="continuous" & V2_class=="nominal",
                    paste("with(data, sqrt(summary(lm(", V1, "~", V2, "))$r.squared))"),
                    ifelse(V1_class=="nominal" & V2_class=="continuous",
                           paste("with(data, sqrt(summary(lm(", V2, "~", V1, "))$r.squared))"),
                           r)),
           r=ifelse(cor_type=="kruskal",
                    paste("with(summarise(group_by(select(data,", V1, ",", V2,"),",V1, ",",V2,"),Freq=n()), Lambda(xtabs(Freq~",V1, "+", V2,")))"),
                    r),
           r=ifelse(V1_class=="ordinal" & V2_class=="nominal",
                    paste("with(data, sqrt(summary(lm(as.integer(", V1, ")~", V2, "))$r.squared))"),
                    ifelse(V1_class=="nominal" & V2_class=="ordinal",
                           paste("with(data, sqrt(summary(lm(as.integer(", V2, ")~", V1, "))$r.squared))"),
                           r)),
           r=ifelse(V1_class=="ordinal" & V2_class=="binary",
                    paste("wilcoxonRG(x=data$", V1, ", g=data$", V2, ")", sep=""),
                    ifelse(V1_class=="binary" & V2_class=="ordinal",
                           paste("wilcoxonRG(x=data$", V2, ", g=data$", V1, ")", sep=""),
                           r)),
           r=ifelse(grepl("biserial", r) | grepl("point-biserial", r)| grepl("polychoric", r), paste(r, "$rho", sep=""), 
                    ifelse(grepl("pearson", r) | grepl("tetrachoric", r), paste(r, "$r", sep=""), r)))
  suppressMessages({
    cors <- sapply(cor_types$r, function(x){
      eval(parse(text=x))
    }) %>% 
      unname})
  
  cor_types$r <- cors
  cor_types <- cor_types %>% 
    select(V1, V2, r) 
  
  df2 <- data.frame(V1=c(cor_types[1,1], last(cor_types$V2)),
                    V2=c(cor_types[1,1], last(cor_types$V2)),
                    r=NA)
  
  cor_types <- do.call(rbind, list(df2[1,], cor_types)) 
  cor_types <- do.call(rbind, list(cor_types, df2[2,]))
  cor_types <- cor_types %>% 
    pivot_wider(names_from=V2, values_from=r) %>% 
    rename(rowname=V1)
  cor_types <- as.matrix(cor_types[,-1])
  cor_types[lower.tri(cor_types)] <- t(cor_types)[lower.tri(t(cor_types))]
  
  cormat <- cor_types %>% 
    as.data.frame() %>% 
    mutate(rowname=names(.)) %>% 
    select(rowname,names(.))
  
  cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
      for (j in (i + 1):n) {
        tmp <- cor.test(mat[, i], mat[, j], ...)
        p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
      }
    }
    colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
    p.mat
  }
  cormat2 <- as.matrix(cormat[,-1])
  diag(cormat2) <- 1
  row.names(cormat2) <- cormat$rowname
  p.mat <- cor.mtest(cormat2)
  plot2 <- corrplot(corr=cormat2, p.mat=p.mat, type="lower",  
                    sig.level = 0.05, diag = T, method="color",
                    addCoef.col = "black", number.cex=.8, tl.col = "black", 
                    order = "original", tl.srt=45, pch="X",pch.col = "firebrick1", addrect = 3)
  plot1 <- network_plot(cormat)
  diag(cormat[,-1]) <- 1
  
  list(cormat=cormat, network=plot1, probability_plot=plot2)
  
}
starwars %>% 
  na.omit %>% 
  select(-name) %>% 
  clases(.) 
mtcars %>% 
  #mutate(vs=as.factor(vs)) %>% 
  clases()

df %>% 
  clases
plot(mtcars$vs, mtcars$cyl)
select(starwars, types$continuous)
```

```{r}
cormat2 %>% min
cor(mtcars)

as.data.frame(correlation(mutate(select(mtcars,cyl,vs), vs=vs), method='point-biserial'))$rho
```

```{r}
library(rcompanion)
data(Catbus)
wilcox.test(Steps ~ Sex, data = Catbus)
wilcoxonRG(x = Catbus$Steps, g = Catbus$Sex)
wilcoxonRG(x = df$ordi1, g = df$bin1)
# example from Goodman Kruskal (1954)
library(DescTools)
prova <- df %>% 
  select(bin1, ordi1) %>% 
  group_by(bin1, ordi1) %>% 
  summarise(Freq=n())
m <- xtabs(Freq ~ bin1 + ordi1, prova)
# direction default is "symmetric"
Lambda(m)
Lambda(m, conf.level=0.95)

Lambda(m, direction="row")
Lambda(m, direction="column")
descriptive_plot(mtcars, all)
```

```{r}
#method="pearson"
#method="kendall"
#method="spearman"
#method="biserial"
#method="polychoric"
#method="tetrachoric"
#method="biweight"
#method="distance"
#method="percentage"
#method="shepherd"

```


```{r}
descriptive_plot <- function(data,...){
    vars <- select(data,...) %>% 
        as.list
    
    plot_fun <- function(variables){
        dens1 <- density(variables)
        
        pos_median <- which(dens1$x>=quantile(variables, .25) & dens1$x <= quantile(variables, .75))
        
        sigmas <- function(var){
            median <- median(var)
            c(-4*sd(var)+median,-3*sd(var)+median,-2*sd(var)+median,-sd(var)+median, 
              median, 
              sd(var)+median, 2*sd(var)+median, 3*sd(var)+median, 4*sd(var)+median)
        }
        
        descr_plot <- ggplot(mapping = aes(x=variables))+
            geom_density(color="red", fill="deepskyblue1")+
            scale_x_continuous(expand = c(0, 0), limits=range(dens1$x), 
                               sec.axis = dup_axis(name="",
                                                   breaks = c(sigmas(variables)),
                                                   labels = c(expression(paste(-4, sigma)),
                                                              expression(paste(-3, sigma)),
                                                              expression(paste(-2, sigma)),
                                                              expression(paste(-1, sigma)),
                                                              expression(paste(0, sigma)),
                                                              expression(paste(1, sigma)),
                                                              expression(paste(2, sigma)),
                                                              expression(paste(3, sigma)),
                                                              expression(paste(4, sigma)))))+
            scale_y_continuous(expand = c(0, 0))+
            theme_classic()+
            theme(axis.text.y=element_blank(),
                  axis.line.y=element_blank(),
                  axis.ticks.y=element_blank(),
                  axis.title.y = element_blank(),
                  panel.grid.major.x = element_line(linetype = "longdash", color = "black"))+
            geom_area(data = with(dens1, data.frame(x, y))[pos_median,],
                      aes(x=x, y=y),
                      fill="dodgerblue4")+
            geom_vline(xintercept = c(min(variables), 
                                      quantile(variables, probs = c(.25,.75)), 
                                      max(variables)), 
                       linetype="twodash", color = "blue")+
            geom_vline(xintercept = sigmas(variables), linetype="dashed", color="darkorange2")+labs(x="")
        
        measures <- data.frame(Min=min(variables), Q1=quantile(variables, .25), Median=quantile(variables, .5),
                                   Q3=quantile(variables, .75), Max=max(variables), SD=sd(variables),
                                   Kurtosis=kurtosis(variables), Skweness=skewness(variables)) %>% 
            mutate_all(round, 2) %>% 
            ggtexttable(., rows = NULL, 
                        theme = ttheme("mBlue"))
        
        ggarrange(descr_plot, measures,
                  ncol = 1, nrow = 2,
                  heights = c(3, 0.5))
    }
    
    lapply(vars, plot_fun)
}
k <- descriptive_plot(datos, var1, var3) 
k
```

```{r}
descriptive_plot <- function(data,...){
    vars <- select(data,...) %>%
        as.list

    plot_fun <- function(variables, name_x){
        dens1 <- density(variables)

        pos_median <- which(dens1$x>=quantile(variables, .25) & dens1$x <= quantile(variables, .75))

        sigmas <- function(var){
            median <- median(var)
            c(-4*sd(var)+median,-3*sd(var)+median,-2*sd(var)+median,-sd(var)+median,
              median,
              sd(var)+median, 2*sd(var)+median, 3*sd(var)+median, 4*sd(var)+median)
        }

        descr_plot <- ggplot(mapping = aes(x=variables))+
            geom_density(color="red", fill="deepskyblue1")+
            scale_x_continuous(expand = c(0, 0), limits=range(dens1$x),
                               sec.axis = dup_axis(name="",
                                                   breaks = c(sigmas(variables)),
                                                   labels = c(expression(paste(-4, sigma)),
                                                              expression(paste(-3, sigma)),
                                                              expression(paste(-2, sigma)),
                                                              expression(paste(-1, sigma)),
                                                              expression(paste(0, sigma)),
                                                              expression(paste(1, sigma)),
                                                              expression(paste(2, sigma)),
                                                              expression(paste(3, sigma)),
                                                              expression(paste(4, sigma)))))+
            scale_y_continuous(expand = c(0, 0))+
            theme_classic()+
            theme(#axis.text.y=element_blank(),
                #axis.line.y=element_blank(),
                #axis.ticks.y=element_blank(),
                #axis.title.y = element_blank(),
                panel.grid.major.x = element_line(linetype = "longdash", color = "black"))+
            geom_area(data = with(dens1, data.frame(x, y))[pos_median,],
                      aes(x=x, y=y),
                      fill="dodgerblue4")+
            geom_vline(xintercept = c(min(variables),
                                      quantile(variables, probs = c(.25,.75)),
                                      max(variables)),
                       linetype="twodash", color = "blue")+
            geom_vline(xintercept = sigmas(variables), linetype="dashed", color="darkorange2")+
            labs(x=name_x)

        measures <- data.frame(Min=min(variables), Q1=quantile(variables, .25), Median=quantile(variables, .5),
                               Q3=quantile(variables, .75), Max=max(variables), SD=sd(variables),
                               Kurtosis=kurtosis(variables), Skweness=skewness(variables)) %>%
            mutate_all(round, 2) %>%
            ggtexttable(., rows = NULL,
                        theme = ttheme("mBlue", base_size = 10,padding = unit(c(6,3), "mm")))

        ggarrange(descr_plot, measures,
                  ncol = 1, nrow = 2,
                  heights = c(3, .5))
    }

    suppressWarnings(mapply(plot_fun, name_x=names(vars), variables=vars, SIMPLIFY = FALSE))
}

```


